Try to connect redis
davidfloegel/overtones-game-redis pull request #3
Opened 2021-05-09 14:57 UTC by cle-ment

2021-05-11 07:07 UTC, davidfloegel requested changes
there's a `.use-playback.ts.swp` file - did I create that or you? That should be removed.

Otherwise this looks awesome!! can't wait to try 😁

2021-05-11 07:07 UTC, davidfloegel commented on pages/api/finish-game.ts
> +  const lb = new Leaderboard(redis, 'lb:example', {
I think we should move this into `redis.ts`, i.e.

```
export const harmonicLeaderboard = new Leaderboard....
```

and then here
````
import { harmonicLeaderboard } from 'lib/redis'
```

because then it can be re-used in the `hello.ts`

2021-05-11 07:07 UTC, davidfloegel commented on pages/api/finish-game.ts
> +    const lastScore = lastScoreOrNull ? lastScoreOrNull : 0
```suggestion
    const lastScore = lastScoreOrNull || 0
```

2021-05-11 07:07 UTC, davidfloegel commented on pages/api/finish-game.ts
> +    const lastRank = lastRankOrNull ? lastRankOrNull : 0
```suggestion
    const lastRank = lastRankOrNull || 0
```

2021-05-11 07:07 UTC, davidfloegel commented on pages/api/finish-game.ts
> +  const lb = new Leaderboard(redis, 'lb:example', {
maybe?
```suggestion
  const lb = new Leaderboard(redis, 'lb:alltime', {
```

2021-05-11 07:07 UTC, davidfloegel commented on pages/api/hello.ts
> +  const lb = new Leaderboard(redis, 'lb:example', {
same here, should get that from the `redis.ts` file as mentioned above

2021-05-11 12:50 UTC, cle-ment commented on pages/api/hello.ts
> +  const lb = new Leaderboard(redis, 'lb:example', {
Done!

2021-05-11 12:53 UTC, cle-ment commented on pages/api/finish-game.ts
> +    const lastScore = lastScoreOrNull ? lastScoreOrNull : 0
Didn't know that's a thing, nice!

2021-05-11 13:02 UTC, cle-ment commented
Cool I think I addressed the changes :) Should we merge?

2021-05-12 06:42 UTC, davidfloegel commented on lib/redis.ts
> +    if (user != "" && password != "") {
```suggestion
    if (password) {
```

2021-05-12 06:51 UTC, cle-ment commented
Fix 

- [ ] this:

![IMAGE 2021-05-12 09:50:40](https://user-images.githubusercontent.com/1208780/117931152-83a98500-b307-11eb-979d-ecf7b395ee17.jpg)

vs 

![IMAGE 2021-05-12 09:50:58](https://user-images.githubusercontent.com/1208780/117931193-8e641a00-b307-11eb-9c1e-8341080594ec.jpg)

2021-05-12 06:52 UTC, cle-ment commented on lib/redis.ts
> +    if (user != "" && password != "") {
Does this check for empty string as well?

2021-05-14 08:53 UTC, merged